// Revenue-rec-side attribution for the portfolio-wide DSR export bundle.
//
// Privacy TSC. Implements the contract described at
// `docs/policies/data-subject-requests.md` → "Right of access".
//
// This function is INVOKED FROM ledger-core's `buildUserDataExport()`
// when a subject's Article 15 request is being assembled. Revenue-rec
// is the canonical home for ASC 606 contract + revenue-recognition
// data; this helper returns **attribution counts only**, never the
// underlying tenant data.
//
// Counterparty PII (signatories on `ContractDocument.rawText`) is the
// TENANT's data; we are the processor, not the controller. A
// counterparty asking for erasure must be routed to the tenant (per
// the DSR doc's "Edge cases" section).
//
// =========================================================================
// HYBRID IMPLEMENTATION — partial wiring + documented schema gaps
// =========================================================================
//
// The v0.2 schema carries attribution columns for TWO of the five
// counts; the other three are schema gaps backed by ledger-core's
// audit_log (similar to fa-amort's full delegation pattern).
//
//   WIRED:
//   - `contractDocumentsUploaded` ← `ContractDocument.uploadedBy`
//   - `recognitionSchedulesApproved` ← `RecognitionEvent.postedBy`
//     (semantically: the schedule is auto-generated by extractor
//     approval; the human-authorization moment is when a PLANNED
//     schedule gets posted to ledger-core, captured in
//     `RecognitionEvent.postedBy`)
//
//   GAPS (return 0; documented):
//   - `revenueContractsCreated` — `RevenueContract` has no `createdBy`
//     column. Manual creation isn't wired in v0.2; future Server
//     Action lands the column. Authoritative attribution lives in
//     ledger-core's audit_log for AI-extraction-approved contracts.
//   - `aiExtractionsAccepted` — `AiExtractionSuggestion` records the
//     model output but has no `acceptedBy`/`rejectedBy` decision
//     column. The `approveExtractionAction` Server Action knows the
//     userId but doesn't persist it on the suggestion row.
//   - `aiExtractionsRejected` — same gap as accepted.

import type { PrismaClient } from "@prisma/client";

/**
 * Attribution counts for a user across revenue-rec's tables.
 *
 * Stable schema — ledger-core's export bundle persists these counts
 * verbatim. Adding a new top-level key is backwards-compatible.
 * `revenueContractsCreated`, `aiExtractionsAccepted`, and
 * `aiExtractionsRejected` are zeros today (schema gap — see file's
 * HYBRID IMPLEMENTATION note).
 */
export interface RevenueRecAttribution {
  /**
   * Revenue contracts the subject created. **Always 0 today**:
   * `RevenueContract` has no `createdBy` column in v0.2. AI-extracted
   * contracts have their human-approval attribution in ledger-core's
   * audit_log; manual creation isn't wired.
   */
  revenueContractsCreated: number;
  /**
   * Contract documents the subject uploaded. Counts `ContractDocument`
   * rows where `uploadedBy = userId`. Does NOT include `rawText`
   * (the highest-sensitivity column in the portfolio — counterparty
   * PII; the tenant is the controller, not the subject).
   */
  contractDocumentsUploaded: number;
  /**
   * Recognition events the subject posted. Counts `RecognitionEvent`
   * rows where `postedBy = userId`. Semantically: this is the
   * human-authorization moment for revenue recognition — the subject
   * clicked "Post" on a PLANNED schedule row, the bridge sent the JE
   * to ledger-core, and a `RecognitionEvent` was written to log it.
   *
   * Named `recognitionSchedulesApproved` for interface stability;
   * the v0.1 stub interface promised this name and downstream
   * `buildUserDataExport()` keys off it.
   */
  recognitionSchedulesApproved: number;
  /**
   * AI extractions the subject accepted. **Always 0 today**:
   * `AiExtractionSuggestion` has no `acceptedBy` column.
   * `approveExtractionAction` does emit an audit log row in ledger-
   * core, so the canonical attribution lives there.
   */
  aiExtractionsAccepted: number;
  /**
   * AI extractions the subject rejected. **Always 0 today**: same
   * schema-gap story as `aiExtractionsAccepted`.
   */
  aiExtractionsRejected: number;
  /** When the count snapshot was taken (ISO 8601 UTC). */
  snapshotAt: string;
}

/**
 * Assemble revenue-rec's attribution contribution to the portfolio-
 * wide DSR export bundle.
 *
 * Caller: `ledger-core/src/lib/privacy/user-data.ts buildUserDataExport()`.
 * Called via HTTP at a future `/api/internal/dsr/attribution` endpoint
 * gated by `INTERNAL_API_TOKEN`.
 *
 * Authorization: enforced at the calling Server Action layer in
 * ledger-core. This helper is the data-assembly seam, not the
 * authorization gate.
 *
 * Two parallel queries today (one per wireable column). Schema gaps
 * return 0. When the gaps close (createdBy on RevenueContract,
 * acceptedBy/rejectedBy on AiExtractionSuggestion), add new
 * `Promise.all` entries — the interface shape stays stable.
 *
 * @param prisma - Prisma client (typically the revenue-rec singleton)
 * @param userId - Subject user UUID. Matched against `uploadedBy`
 *                 and `postedBy` attribution columns.
 * @returns Attribution counts. Three fields are always zero (see
 *          HYBRID IMPLEMENTATION note).
 */
export async function revenueRecAttribution(
  prisma: PrismaClient,
  userId: string
): Promise<RevenueRecAttribution> {
  const [contractDocumentsUploaded, recognitionSchedulesApproved] =
    await Promise.all([
      prisma.contractDocument.count({ where: { uploadedBy: userId } }),
      prisma.recognitionEvent.count({ where: { postedBy: userId } }),
    ]);

  return {
    // Schema gap — see file's HYBRID IMPLEMENTATION note.
    revenueContractsCreated: 0,
    contractDocumentsUploaded,
    recognitionSchedulesApproved,
    // Schema gap — see file's HYBRID IMPLEMENTATION note.
    aiExtractionsAccepted: 0,
    aiExtractionsRejected: 0,
    snapshotAt: new Date().toISOString(),
  };
}

/**
 * Retained for backwards compatibility with the v0.1 typed-stub
 * tests + any caller that imported it during the stub era. Real
 * callers will not see this thrown — the implementation above no
 * longer throws.
 */
export class NotImplementedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "NotImplementedError";
  }
}
