// Revenue-rec-side attribution for the portfolio-wide DSR export bundle.
//
// Privacy TSC. Implements the contract described at
// `docs/policies/data-subject-requests.md` → "Right of access".
//
// This function is INVOKED FROM ledger-core's `buildUserDataExport()`
// when a subject's Article 15 request is being assembled. Revenue-rec
// is the canonical home for ASC 606 contract + revenue-recognition
// data; this helper returns **attribution counts only**, never the
// underlying tenant data.
//
// Counterparty PII (signatories on `ContractDocument.rawText`) is the
// TENANT's data; we are the processor, not the controller. A
// counterparty asking for erasure must be routed to the tenant (per
// the DSR doc's "Edge cases" section).
//
// =========================================================================
// FULL-WIRE IMPLEMENTATION — 4 of 5 counts wired, 1 delegated to audit_log
// =========================================================================
//
// 2026-06-05 update: schema additions in PR #24 + helper update in this
// PR flip 2 of the 3 prior schema gaps from honest-zero to real counts.
// The helper now queries 4 owned-table columns + leaves 1 delegated to
// ledger-core's audit_log. Closes v2.1 deficiency #26.
//
//   WIRED (4 of 5):
//   - `contractDocumentsUploaded` ← `ContractDocument.uploadedBy`
//   - `recognitionSchedulesApproved` ← `RecognitionEvent.postedBy`
//     (semantically: the schedule is auto-generated by extractor
//     approval; the human-authorization moment is when a PLANNED
//     schedule gets posted to ledger-core, captured in
//     `RecognitionEvent.postedBy`)
//   - `aiExtractionsAccepted` ← `AiExtractionSuggestion.acceptedBy`
//     (NEW 2026-06-05). The `approveExtractionAction` Server Action
//     now writes `acceptedBy = currentUser.id` + `acceptedAt = now`
//     atomically with contract approval.
//   - `aiExtractionsRejected` ← `AiExtractionSuggestion.rejectedBy`
//     (NEW 2026-06-05). Reserved for a future `rejectExtractionAction`
//     that explicitly marks rejection (today's flow doesn't reject;
//     a "re-extract" action would). Helper counts existing values
//     today, returns 0 until callers populate.
//
//   STILL DELEGATED (1 of 5):
//   - `revenueContractsCreated` — `RevenueContract` has no `createdBy`
//     column. Manual creation isn't wired today; future Server Action
//     lands the column. AI-extraction-approved contracts surface in
//     ledger-core's audit_log via the `approveExtractionAction` audit
//     emission, so the attribution chain is preserved at the portfolio
//     level. Closes when manual contract creation lands.

import type { PrismaClient } from "@prisma/client";

/**
 * Attribution counts for a user across revenue-rec's tables.
 *
 * Stable schema — ledger-core's export bundle persists these counts
 * verbatim. Adding a new top-level key is backwards-compatible.
 * `revenueContractsCreated`, `aiExtractionsAccepted`, and
 * `aiExtractionsRejected` are zeros today (schema gap — see file's
 * HYBRID IMPLEMENTATION note).
 */
export interface RevenueRecAttribution {
  /**
   * Revenue contracts the subject created. **Still 0 today** (delegated
   * to ledger-core's audit_log): `RevenueContract` has no `createdBy`
   * column. AI-extraction-approved contracts surface in audit_log via
   * `approveExtractionAction`'s emission. Manual creation isn't wired.
   */
  revenueContractsCreated: number;
  /**
   * Contract documents the subject uploaded. Counts `ContractDocument`
   * rows where `uploadedBy = userId`. Does NOT include `rawText`
   * (the highest-sensitivity column in the portfolio — counterparty
   * PII; the tenant is the controller, not the subject).
   */
  contractDocumentsUploaded: number;
  /**
   * Recognition events the subject posted. Counts `RecognitionEvent`
   * rows where `postedBy = userId`. Semantically: this is the
   * human-authorization moment for revenue recognition — the subject
   * clicked "Post" on a PLANNED schedule row, the bridge sent the JE
   * to ledger-core, and a `RecognitionEvent` was written to log it.
   *
   * Named `recognitionSchedulesApproved` for interface stability;
   * the v0.1 stub interface promised this name and downstream
   * `buildUserDataExport()` keys off it.
   */
  recognitionSchedulesApproved: number;
  /**
   * AI extractions the subject accepted. Counts
   * `AiExtractionSuggestion` rows where `acceptedBy = userId`. The
   * `approveExtractionAction` Server Action writes `acceptedBy`
   * atomically with contract approval (2026-06-05).
   */
  aiExtractionsAccepted: number;
  /**
   * AI extractions the subject rejected. Counts
   * `AiExtractionSuggestion` rows where `rejectedBy = userId`. Reserved
   * for a future `rejectExtractionAction` (the current "re-extract"
   * flow replaces rather than rejects); today's count is real but
   * usually 0 until callers populate.
   */
  aiExtractionsRejected: number;
  /** When the count snapshot was taken (ISO 8601 UTC). */
  snapshotAt: string;
}

/**
 * Assemble revenue-rec's attribution contribution to the portfolio-
 * wide DSR export bundle.
 *
 * Caller: `ledger-core/src/lib/privacy/user-data.ts buildUserDataExport()`.
 * Called via HTTP at a future `/api/internal/dsr/attribution` endpoint
 * gated by `INTERNAL_API_TOKEN`.
 *
 * Authorization: enforced at the calling Server Action layer in
 * ledger-core. This helper is the data-assembly seam, not the
 * authorization gate.
 *
 * Four parallel queries (one per wireable column). The remaining
 * `revenueContractsCreated` returns 0 until manual contract creation
 * is wired with a `createdBy` column.
 *
 * @param prisma - Prisma client (typically the revenue-rec singleton)
 * @param userId - Subject user UUID. Matched against `uploadedBy`,
 *                 `postedBy`, `acceptedBy`, and `rejectedBy`
 *                 attribution columns.
 * @returns Attribution counts. One field still defaults to zero (see
 *          FULL-WIRE IMPLEMENTATION note for the audit_log delegation).
 */
export async function revenueRecAttribution(
  prisma: PrismaClient,
  userId: string
): Promise<RevenueRecAttribution> {
  const [
    contractDocumentsUploaded,
    recognitionSchedulesApproved,
    aiExtractionsAccepted,
    aiExtractionsRejected,
  ] = await Promise.all([
    prisma.contractDocument.count({ where: { uploadedBy: userId } }),
    prisma.recognitionEvent.count({ where: { postedBy: userId } }),
    prisma.aiExtractionSuggestion.count({ where: { acceptedBy: userId } }),
    prisma.aiExtractionSuggestion.count({ where: { rejectedBy: userId } }),
  ]);

  return {
    // Delegated to ledger-core audit_log — see file note.
    revenueContractsCreated: 0,
    contractDocumentsUploaded,
    recognitionSchedulesApproved,
    aiExtractionsAccepted,
    aiExtractionsRejected,
    snapshotAt: new Date().toISOString(),
  };
}

/**
 * Retained for backwards compatibility with the v0.1 typed-stub
 * tests + any caller that imported it during the stub era. Real
 * callers will not see this thrown — the implementation above no
 * longer throws.
 */
export class NotImplementedError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "NotImplementedError";
  }
}
